name: setup-sdk

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
    - uses: actions/checkout@v2
    - name: tools
      run: |
        pip3 install end
        python3 --version

    - name: download
      run: |
        wget https://aka.ms/AzureSphereSDKInstall/Linux -O install.sh
        chmod +x install.sh
        sudo apt-get install -y net-tools curl ninja-build
        yes Y | sudo ./install.sh

    - name: arm-rt-toolchain
      run: |
        wget ${TOOLCHAIN_URL} -O tc.tar.bz2
        tar xf ${TOOLCHAIN_DIR}.tar.bz2 --strip-components=1
        echo "PWD:"pwd
        echo "GITHUB_WORKSPACE:" ${GITHUB_WORKSPACE}
      env:
        TOOLCHAIN_DIR: "arm-tool-chain"
        TOOLCHAIN_URL: "https://developer.arm.com/-/media/Files/downloads/gnu-rm/9-2019q4/gcc-arm-none-eabi-9-2019-q4-major-x86_64-linux.tar.bz2"

    - name: build
      run: |
        cd Samples/AzureIoT
        mkdir $CMAKE_DIR
        cd $CMAKE_DIR
        pwd
        echo hoge ${CMAKE_DIR}
        cmake -G "Ninja" -DCMAKE_TOOLCHAIN_FILE="/opt/azurespheresdk/CMakeFiles/AzureSphereToolchain.cmake" -DAZURE_SPHERE_TARGET_API_SET="4" -DAZURE_SPHERE_TARGET_HARDWARE_DEFINITION_DIRECTORY="${GITHUB_WORKSPACE}/Hardware/mt3620_rdb" -DAZURE_SPHERE_TARGET_HARDWARE_DEFINITION="sample_hardware.json" --no-warn-unused-cli -DCMAKE_BUILD_TYPE="Debug" -DCMAKE_MAKE_PROGRAM="ninja" ..
        ninja
        ls
      env:
        CMAKE_DIR: build

    - name: build_rt
      run: |
        cd ${PROJECT}
        mkdir ${CMAKE_DIR}
        cd ${CMAKE_DIR}
      env: PROJECT: "Samples/IntercoreComms/IntercoreComms_RTApp_MT3620_BareMetal"

    env:
      CMAKE_DIR: build
